application: go-card
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app

- url: /manifest.appcache
  script: _go_app

- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "0s"

- url: /(.*)/
  static_files: static/\1/index.html
  upload: static/.*/index.html
  expiration: "0s"

- url: /(.*)
  static_files: static/\1
  upload: static/.*

pagespeed:
  domains_to_rewrite:
  - go-card.appspot.com
  enabled_rewriters:
  - ProxyCss
  - ProxyImages
  - ProxyJs
  - InlineCss
  - InlineJs
  - InlineImages
  - CollapseWhitespace
  - RemoveComments
  - RemoveQuotes
  - CombineCss
  - MinifyCss
  - WebpOptimization
  - ImageRecompressJpeg
  - ImageProgressiveJpeg
  - ImageRecompressPng
  - ImageStripMetadata
  - ImageStripColorProfile
  - CombineJs
  - JsOptimize
  disabled_rewriters:
  - ConvertMetaTags
  - InlinePreviewImages
  - CombineHeads
  - ElideAttributes
  - LeftTrimUrls
  - MoveCssToHead
  - ImageConvertToJpeg
  - ImageResize
  - LazyloadImages
  - ImageAddDimensions
  - DeferJs
